### ISSUE TITLE
Performance Problem: Some times Trickster request too much time range than needed.

### ISSUE THREAD

**Issue by qwertwwwe** [Comcast/trickster#131]
In our use case, some times Trickster will request more time range than needed. For example, I set the MaxValueAgeSecs=86400(24h). The first request time range is 2019.01.29-2019.01.30, the second request time range is 2019.01.01-2019.01.02. In the second request, Trickster will send request to prometheus with time range 2019.01.01-2019.01.29, some times this length of time range will cause timeout in query. If trickster optimize this case, I think this may improve a lot of performance in some query cases.

**Comment by jranson** [comment]
@qwertwwwe In the `next` branch you can see that we have implemented this enhancement in `internal/proxy/deltaproxycache.go` and it will be part of the 1.0 release. The proxy will no longer have any condition where it requests more data than the client requests, while the gaps in the cache are maintained and filled in only when requested by the client. We are hoping to have a 1.0 beta release in the next few weeks so that you can try it out.

**Comment by qwertwwwe** [comment]
@jranson  That's great, this will solve our performance problem directly.

**Comment by jacksontj** [comment]
FYI, we ran into the same problem -- I have opened #198 with a fix for at least the case we are seeing.
