### ISSUE TITLE
Cors problem on 1.0-beta

### ISSUE THREAD

**Issue by Dudesons** [Comcast/trickster#193]
Hi,

it seems on trickster `1.0-beta` there is a problem with cors origin.
I'm running trickster inside a container.

I tried to setup this one with grafana and I have cors error.
<img width="1293" alt="Screenshot 2019-04-10 at 10 50 41" src="https://user-images.githubusercontent.com/3831949/55867271-7ba81580-5b82-11e9-9552-6e04236bbd45.png">

Maybe I miss something in the configuration.

my config:
```
[caches]

    [caches.default]
    type = 'redis_cluster'
    compression = true
    timeseries_ttl_secs = 21600
    fastforward_ttl_secs = 15
    object_ttl_secs = 30
        [caches.default.index]
        reap_interval_secs = 3
        flush_interval_secs = 5
        max_size_bytes = 536870912
        max_size_backoff_bytes = 16777216
        max_size_objects = 0
        max_size_backoff_objects = 100

        [caches.default.redis_cluster]
        endpoints = ['${redis_endpoint}']
        password = ''
```

I don't have the problem with version `0.1.7`

**Comment by jranson** [comment]
@Dudesons Damien, thanks for the report! I have entered PR #195 to add back the CORS header that we had been setting in the 0.1.x branch. It looks like you have configured Trickster/Prom in Grafana as direct/browser access mode in rather than via the grafana proxy. Totally legit usecase and we're happy to add back the CORS.  Once PR is merged, we'll spin up another beta release for you to confirm it is resolved. Thanks again! JR

**Comment by jranson** [comment]
@Dudesons the `1.0-beta3` release image is added and `1.0-beta` tag is refreshed (if you just want to re-pull) and should address. this. thanks again!
