### ISSUE TITLE
v1.0.5-beta5

### ISSUE THREAD

**Issue by sylr** [Comcast/trickster#223]
I think there has been a mistake with the naming of the tags for the v1.0.0 beta line

v1.0.5-beta5 means beta5 toward v1.0.5.

It should have been: 

- v1.0.0-beta1
- v1.0.0-beta2
- v1.0.0-beta3
- v1.0.0-beta4
- v1.0.0-beta5

Regards.

**Comment by jranson** [comment]
@sylr thanks for the report. The next time we have a beta cycle, we'll make the versioning more clear.

The purpose of incrementing the the semantic version is so that we can quickly see the version in an issue report's output logs while troubleshooting issues that are reported. If we did not increment the semantic version, Trickster it would report 1.0.0 for all beta releases, and that could be confusing.

The next time we re-enter beta after 1.0, I'll make sure to address this by adding an additional field, separate from the version field, that contains information about pre-release builds when needed. Then we can adopt the recommended versioning convention.

For now, however, as we are 5 beta releases deep, it is likely more confusing to users to modify the naming than it is to leave it alone. I will keep the issue open until we have pre-release field ready as described above.

**Comment by sylr** [comment]
The problem here is that if you release 1.0.0 now people might install 1.0.x-betax because they will think it’s newer than 1.0.0.
