### ISSUE TITLE
Problem in Grafana variables

### ISSUE THREAD

**Issue by lohmag** [Comcast/trickster#228]
When I use trickster in grafana variables as datasource there is problem when you use variable in variable like this:
```

$host | label_values(pg_up{job=~"postgres-exporter-.*"}, instance)
$instance | label_values(pg_static{instance=~"$host", job=~"postgres-exporter-.*"}, server) 
$datname | label_values(pg_locks_count{instance=~"$host", server=~"$instance"}, datname)
```
In $instance and $datname is no data or some not valid data seem like it not updating. When I use Prometheus directly all works fine.

**Comment by jranson** [comment]
Hey @lohmag can you please share which version of Trickster you are using? Thanks!

**Comment by raffraffraff** [comment]
I may be seeing a different issue, but the outcome is 'screwed up Grafana variables'. The nub of my issue is that Trickster appears to be returning cached results for the _previous_ label_values query.

Example: I have two variables, dc (datacenter) and role. The queries for them are as follows:

`label_values(system_uptime{role=~"consul|bastion"}, dc)`
The system_uptime metric from all 'consul' and 'bastion' roles returns a small set of hosts that exist in all datacenters.

`label_values(system_n_cpus{dc=~"$dc"}, role)`
This returns all _roles_ in the $dc datacenter. (I use a _different_ metric to make troubleshooting this issue more obvious)

When I configure this dashboard to use Promxy directly, the variables work fine. When I configure the dashboard to use Trickster (which sits right in front of Promxy), my variables are all screwed up. I see the following behavior in the browser's developer tools:

Request URL:  https://grafana.domain/api/datasources/proxy/2/api/v1/series?match[]=system_n_cpus{dc=~"eu1"}&start=1559223299&end=1559234099

Results: 
```
data | […]
-- | --
0 | {…}
__name__ | system_uptime
dc | eu1
host | consul1.eu1
role | consul
-- | --
1 | {…}
__name__ | system_uptime
dc | us1
host | consul1.us1
role | consul
-- | --
2 | {…}
__name__ | system_uptime
dc | ap1
host | consul1.ap1
role | consul
-- | --
3 | {…}
__name__ | system_uptime
dc | eu1
host | bastion1.eu1
role | consul
-- | --
4 | {…}
__name__ | system_uptime
dc | us1
host | bastion1.us1
role | consul
-- | --
5 | {…}
__name__ | system_uptime
dc | ap1
host | bastion1.ap1
role | consul
-- | --
```

So, my browser sends a query for system_n_cpus in the 'eu1' datacenter, but it gets back results for the previous 'system_uptime' query, which specified just 2 roles. So instead of getting a full list of all roles in eu1, I just get those two.

I'm currently using the latest Trickster 1.0 beta 5

**Comment by lohmag** [comment]
> Hey @lohmag can you please share which version of Trickster you are using? Thanks!

1.0.0 beta 5

**Comment by jranson** [comment]
This is potentially related to caching requests to  the Prometheus `series` endpoint (#73). I will revisit that feature request and make sure it is working properly.

**Comment by jranson** [comment]
@lohmag this should be all fixed up in the next beta release which we'll cut later today (we  have one more merge to come in first).
