### ISSUE TITLE
Empty query and query_range results are not cached

### ISSUE THREAD

**Issue by jtorkkel** [Comcast/trickster#238]
Prometheus query or range_query results are not cached when response contain only empty list.
This will result that dashboards having non zero are reloaded fast from cache, whereas dashboards having one or more non zero query are always slow due lack of caching. 
Trickster should also cache empty response, maybe this should be enabled/disabled through cache config.
Tested in v1.0.7-Beta7.

Example response
{
         status: "success",
         data: 
        {
            resultType: "matrix",
            result: [ ]
        }
}

**Comment by jranson** [comment]
@jtorkkel Thanks for finding and reporting this! I have included a patch in PR #240 and it will be fixed in beta8. The main issue was that we were simply looking to see if there were no timestamp values anywhere in the data set to determine if it was cacheable. Instead, now we will check to see if the dataset has any associated time ranges after cropping down to the cache retention policy, and only skip the cache write if it does not. So a data set that has an associated time range but no data will be properly cached. https://github.com/Comcast/trickster/pull/240/files#diff-1f740953ed326d84a614b4e38cbfc654R270
