### ISSUE TITLE
Add warning for potential Redis misconfigurations

### ISSUE THREAD

**Issue by bradleyhession1** [Comcast/trickster#241]
Hi - I've set trickster to cache to redis, I'm using beta 8 (but have tried multiple versions). Trickster seems to connect fine and even tries to store data:

--
time=2019-06-19T12:56:57.101537228Z app=trickster caller=proxy/engines/cache.go:71 level=debug event="compressing cached data" cacheKey=thanos-query:9090.0a9332e4c9046613a62ba8a6e4a2e78a.sz
time=2019-06-19T12:56:57.101899271Z app=trickster caller=cache/redis/redis.go:82 level=debug event="redis cache store" key=thanos-query:9090.0a9332e4c9046613a62ba8a6e4a2e78a.sz
--

However i get no keys in redis and the dashboard(s) load no quicker - I have tried Trickster with the in-memory option and this works as expected.

I am also able to write to redis both using the CLI and an external test application just to rule redis out.

I've also tried standing up multiple Redis types (e.g standard, cluster and sentinel)

Thanks!

**Comment by jranson** [comment]
@bradleyhession1 thanks for this report. Strangely beta8 passed all the unit tests which verifies redis caching works with miniredis.  I will run some manual tests today and try to root cause this.  have you tried any previous betas and found success (that will help me pinpoint where it stopped working)

**Comment by bradleyhession1** [comment]
Hi @jranson We had some success on past Betas - I believe we had redis working shortly before https://github.com/Comcast/trickster/pull/220 was merged.

**Comment by jranson** [comment]
One more ask - can you drop in your config snippet here that is not working?

**Comment by bradleyhession1** [comment]
Sure thing... attached below:

`[caches]
        [caches.default]
        type = "redis"
        timeseries_ttl_secs = 21600
        fastforward_ttl_secs = 15
        object_ttl_secs = 30
        compression = true
            [caches.default.index]
            reap_interval_secs = 3
            flush_interval_secs = 5
            max_size_bytes = 536870912
            max_size_backoff_bytes = 16777216
            max_size_objects = 0
            max_size_backoff_objects = 100
            [caches.default.redis]
            client_type = "standard"
            protocol = "tcp"
            endpoints = ["redis-headless:6379"]
            password = ""
`

**Comment by bradleyhession1** [comment]
I believe i've figured it out - endpoints: should be endpoint for standard - Interesting how it doesn't fatal in or log anything in debug mode. Maybe we just need some better error checking - since it looked like it was working in this case.

**Comment by jranson** [comment]
Great to hear it's working, and that Trickster is bringing value to your deployments. Thanks for trying it out, especially the betas, and giving us the great feedback. 

As you probably figured out, we intentionally used `endpoint` for the clients that require a single  'string' endpoint and `endpoints` for the ones that require a \[ 'list' \] of one or more endpoints. I can definitely send a `WARN` when it looks like there might be an issue with this (e.g., the wrong one config is for the wrong client type); I don't want to fatal it out because - not that I would recommend doing this - I could see people having both values set so they can easily flip between a standard client or a cluster client, by simply changing `client_type`. I will leave this issue open until that warning is added. Thank's for verifying the other redis types as well! If you can give a thumbs up that all looks good, I'll do some cosmetics on the issue to clarify whats up and what we need.

**Comment by jranson** [comment]
@bradleyhession1 The recommended warnings are added to the `next` codebase and will be available in Beta 9 which we are targeting for Monday. Thanks for your patience!

**Comment by jranson** [comment]
@bradleyhession1  A few days late, but we've added the warnings as suggested here. Please let me know if it works as you expect and we'll close out the issue.

**Comment by bradleyhession1** [comment]
Hi @jranson it seems like the latest beta has broken redis now - using the same configuration as previous (which was working in beta8).

I forgot to update this issue but I did test with the Cluster and Sentinel clients on beta8 and all was good.

**Comment by cpower** [comment]
@bradleyhession1 - just tested the 1.0-beta9 release with an AWS Elasticache Redis instance in standard non cluster mode with Prometheus as the origin and it seemed to be working for me.

**Comment by cpower** [comment]
Here's the Redis configuration:

`[caches]

    [caches.default]
    type = 'redis'
    compression = true
    timeseries_ttl_secs = 21600
    fastforward_ttl_secs = 15  
    object_ttl_secs = 30

        [caches.default.index]
        reap_interval_secs = 3 
        flush_interval_secs = 5 
        max_size_bytes = 536870912
        max_size_backoff_bytes = 16777216
        max_size_objects = 0
        max_size_backoff_objects = 100

        [caches.default.redis]
        client_type = 'standard'
        protocol = 'tcp'
        endpoint = 'elasticache.redacted.cache.amazonaws.com:6379'
        sentinel_master = ''
        password = ''
`

**Comment by cpower** [comment]
> A few days late, but we've added the warnings as suggested here. Please let me know if it works as you expect and we'll close out the issue.

Attempted to test Redis endpoint warnings, specifying client.type=redis and using endpoints instead of endpoint does not result in a warning, rather it fails silently and defaults back to memory.
