### ISSUE TITLE
Update configuration example (At least the redis bit)

### ISSUE THREAD

**Issue by carlosjgp** [Comcast/trickster#246]
Thanks to #241 issue I realised why my `redis` configuration was not working

This is by using K8s deployment provided on master

```
[caches]
        [caches.default]
        type = "redis"
        timeseries_ttl_secs = 21600
        fastforward_ttl_secs = 15
        object_ttl_secs = 30
        compression = true
            [caches.default.index]
            reap_interval_secs = 3
            flush_interval_secs = 5
            max_size_bytes = 536870912
            max_size_backoff_bytes = 16777216
            max_size_objects = 0
            max_size_backoff_objects = 100
            [caches.default.redis]
            client_type = "standard"
            protocol = "tcp"
            endpoints = ["redis-headless:6379"]
            password = ""
```

**Comment by jranson** [comment]
@carlosjgp  I am not sure I understand your issue - are you able to reply with the tree URL to the file that needs an update?  Just FYI, since you mention `master` -- the `master` branch's example files are for the 0.1.x release of Trickster. I see your pasted config is for 1.0. Trickster 1.0 is in beta, and everything (code, examples, documentation) is currently in the `next` branch. If you are using the 1.0 Beta release, the master examples will not apply. We'll be merging up to `master` hopefully very soon!

**Comment by carlosjgp** [comment]
Hi @jranson, after reviewing the K8s manifests I copied from `master` branch I realised that it was using the docker image tagged as `latest`. That made me check docker hub and I realised that I was unaware of which release I was using. Then I checked the branches and tags and the configuration file is substantially different, so trying to configure Trickster using the K8s manifests from `master` branch doesn't work as expected to use Redis

Now I'm using an image tag different from `latest`, `1.0-beta7`, and the associated config file and everything works as expected.

Might be a bug on `0.1.10` (`latest`) where Redis configuration was not working :man_shrugging:
