### ISSUE TITLE
Support for Elasticsearch queries from Grafana

### ISSUE THREAD

**Issue by softwareklinic** [Comcast/trickster#341]
Would Trickster work for elasticsearch queries as well

**Comment by jranson** [comment]
@softwareklinic thanks for the question and for your interest in Trickster. I hope you don't mind that I mark this as a duplicate and close, because we actually have an issue open for ElasticSearch support -- #7. So the short answer is, not yet, but we hope to at some point in 2020. I will update #7 when we have more info to share.
