### ISSUE TITLE
Feature: OpenTracing support

### ISSUE THREAD

**Issue by mattbostock** [Comcast/trickster#36]
If Trickster supported tracing, it would be make it easier to see where time is spent in queries across all services involved in serving a query.

Grafana and [Thanos](https://github.com/improbable-eng/thanos) both have some support for tracing:
https://github.com/grafana/grafana/pull/9213

**Comment by jranson** [comment]
@WillGunther for you :) Thanks!!

**Comment by jranson** [comment]
We will be bumping this feature back to v1.1, since the OpenTelemetry libraries are currently barely emergent. We could adopt one of the now-sunsetting solutions from which OpenTelemetry is based and switch later, but that would be a lot of work to introduce a new feature. Targeting late Q3.

**Comment by jranson** [comment]
Revisiting this one. Not sure why it didn't occur to me already, but tracing should certainly be something we implement as an interface, or some other mechanism that makes the underlying tracing implementation (if any) configurable by the Trickster operator, similar to how we already do for Cache type selection.

**Comment by guygrigsby** [comment]
@jranson Is this the one you want me to take a look at? I'll get started right away.

**Comment by jranson** [comment]
:-D Yes please!

**Comment by guygrigsby** [comment]
I have been doing some research and playing with Open Telemetry in Trickster and here are my thoughts.

#### Interfacing
You mentioned above that we create our own interface and provide a reference for wrapping others, ex OpenTelemetry, within our interface. I suggest that we should use the OpenTelemetry API spec directly. Rather than adapting the OpenTelemetry API to our interface, we should adapt other tracing interfaces to OpenTelemetry. This is for the following reasons:

1. Open Telemetry _is_ the interface. Described [here](https://www.cncf.io/blog/2019/05/21/a-brief-history-of-opentelemetry-so-far/) 
> [...] as the next major version of both OpenTracing and OpenCensus

2. An OpenTracing bridge already exists as part of the [Go OpenTelemetry repo](https://github.com/open-telemetry/opentelemetry-go/tree/master/bridge/opentracing).

3. An OpenCensus bridge is on the [release roadmap for OpenTelemetry](https://github.com/open-telemetry/opentelemetry-go#release-schedule), though a date is not given.

#### Implementations

The OpenTelemetry Go client currently has support for 
 - Jaeger and 
 - Stackdriver 

Support for Zipkin is on the way ([roadmap](https://github.com/open-telemetry/opentelemetry-go#release-schedule)). I have been testing with the Jaeger exporter because [the Jaeger all-in-one](https://www.jaegertracing.io/docs/1.9/getting-started/) makes it pretty easy. Personally, I do not have a preference, but I think that Jaeger is more popular so we may want to start there. The OpenTracing SDK also has a stdout exporter, but is likely useful only for testing.

#### Granularity of Span Tracing

I am instrumenting all http handlers via a single shared middleware to start. Additionally, I will instrument all proxied requests, probably via the proxy client. This will give us a broad stroke collection of spans so we can tell where the request call time is spent, internal v external. We will pass the trace info the the origins, but I haven't found any info about passing trace headers to Prometheus and I have not looked at the other origins. Either way, I think we'll be glad we are passing the trace info because I would be surprised if there are not ways to trace within the various origins. Cache tracing will likely only be done from Trickster by timing the cache calls, because Redis does not use http.
 

#### Recommendation Summary for 1.x
 1. We use the OpenTracing API directly and adapt other tracing APIs to it, with the help of the community.
2. Support for Jaeger trace collection
3. Initial trace support will be high level. The example I have been using with promsim looks like the following screen shot. **This is probably still a bit too high, but I would like input from @jranson on the specific operations we want to measure, he knows this service a lot better than I.** :) 

```bash
curl -i 'localhost:8080/test/api/v1/query_range?query=my_test_query{random_label="57",series_count="1"}&start=2&end=2&step=15
```
<img width="1561" alt="image" src="https://user-images.githubusercontent.com/3924641/71328382-ad27fd80-24d3-11ea-9ac3-b4334f6a6677.png">

What does everyone think?

**Comment by guygrigsby** [comment]
@jranson and I spoke offline about my recommendations above and we agreed this is a good place for 1.x. If anyone else has thoughts I would love to hear them.

**Comment by jranson** [comment]
Thanks for looking through this and putting some ideas down.

I think a single high level span, to start, will be fine for this as a first cut in 1.0, and we can add more as we refine the capability. But, we will eventually want these spans, at a minimum: upstream request time; fast forward request time; upstream revalidation request time; cache query time (also recording the query result in the span); cache write time (recording # bytes written into the span). So if that is enough guidance to provide any of those additional spans on the first cut, that's great too :)

As we make upstream HTTP requests to fulfill the client request, in addition to recording those spans in our own trace, we should also properly propagate the inbound client request's trace headers, which Trickster has joined, on to the upstream origin as well, and this may be something that OT cannot do automatically for us as a reverse proxy. Conversely, we should take care to strip any request-level tracing headers from the upstream HTTP response when writing the data to cache, while leaving them in tact for the end-user's response. This will avoid serving unrelated tracing headers downstream of Trickster on subsequent requests for a cached object.

Since Trickster is generally placed into a team's existing platform as an add-on, we want to make configurable to the Trickster operator any/all of the options that OT supports to facilitate that integration. To that end, on the trace collection side, if we support Jaeger collection out-of-the-box, we should have configuration values already defined to indicate the collection backend type, collection endpoint url, etc., which must be set in order to enable delivery to the collection system. Collection should be disabled by default, as the default collection type and endpoint url should be an empty strings and must be explicitly set by the user to enable. Then when OT supports additional backends, such as Zipkin, it will be just a few more lines of code to extend support, as we'd need to just map a collection type name like `zipkin` to the correct OT functionality to extend support.

**Comment by guygrigsby** [comment]
Awesome thanks for the feedback. I got excited about being able see inside Trickster and started adding spans today so we will surely have more than one. I am shooting for everything you listed above.

> upstream request time; fast forward request time; upstream revalidation request time; cache query time (also recording the query result in the span); cache write time (recording # bytes written into the span)

- [x] upstream request time
- [ ] fast forward request time
- [ ] upstream revalidation request time
- [x] cache query time (also recording the query result in the span)
- [ ]  cache write time (recording # bytes written into the span)


Sounds like we are in alignment. Good callout on stripping the the upstream headers before caching.

**Comment by jranson** [comment]
This one is finally released, thanks to @guygrigsby for the excellent work!  More refinements around the content and number of spans will come, but we have a really good start now on the core spans required to bring tracing visibility to the entire application.
