### ISSUE TITLE
Error on unmarshaling cached data

### ISSUE THREAD

**Issue by FUSAKLA** [Comcast/trickster#39]
From time to time Trickster encounters error on unmarshalling data stored in cache.
It does not crash just logs those errors. Also I'm not sure if that means it does not server those data at all or queries the Prometheus to fix this error data?

It happens on for both, the filesystem and memory cache

In log I can see
```
time=2018-04-22T12:19:14.029382922Z app=trickster caller=trickster/handlers.go:445 level=error event="could not unmarshal cached data for this key" key=5afe9f97855959db71d477df683d9348.c837a21ba2b43ebcb924c5c0b23265ed data="{\ufffd{\"status\":\"success\",\"data\":{\"resultType\":\"matrix\",\"\t\u0016\ufffd\":[{\"metric\":{},\"values\":[[1524399120,\"12\"],[\r\u00124420,\"12\"]]}]}}"

```
This is dump of the impacted cache file 
[5afe9f97855959db71d477df683d9348.c837a21ba2b43ebcb924c5c0b23265ed.data.tar.gz](https://github.com/Comcast/trickster/files/1935566/5afe9f97855959db71d477df683d9348.c837a21ba2b43ebcb924c5c0b23265ed.data.tar.gz)

I'm running Trickster `0.0.12` in Kubernetes as proxy for Prometheus 2.2.1 also running in Kubernetes

**Comment by jacksontj** [comment]
@FUSAKLA I was able to repro the failure, and your concern was accurate, this would mean that trickster would return an error and not query prometheus (at least until the cache item went away). I've opened #79 to treat this condition as a cache-miss which will make the cache effectively "self heal" (as corrupted cache objects will be re-fetched).

From looking at the code I don't see a good way for the cache to *become* corrupt, but since trickster has pluggable caches I think it should handle the occasional bad cache value.

**Comment by jranson** [comment]
@FUSAKLA I think we can finally close the loop on this one, as my suspicion is the OOM issues you reported in #56 (fixed from @juliusv is now merged into master, will try to get a release out this weekend) are related to the cache record corruption you reported here. If you're using any cache type other than RAM and Trickster OOM's in the middle of writing a cache record, it would most likely corrupt the record and trigger this condition on subsequent retrievals after Trickster has restarted. So the good news is Julius fixed the OOM issue, and even if the Trickster otherwise quits unexpectedly, #79 from @jacksontj will self-heal it. Sweet. Thanks to everyone's first-rate work on all of these issues.

**Comment by FUSAKLA** [comment]
Great, I'll try the new version with self-healing and freeing the memory and in case it shows up again I'll reopen this but hopefully it won"t show up again. 

Thank you @jacksontj, the cache self-healing feature willl be definatelly usefull even for other cases than just those OOMs.
